import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  type Call,
  type CheckOptions,
  checkSpec,
  type Compiled,
  compile,
  entryFor,
  journeyFunction,
  pageVariable,
  type Problem,
} from "./check.ts";
import { type Config, resolveConfig } from "./config.ts";
import type { Journey } from "./feature.ts";
import { plan, type Planned } from "./moments.ts";
import {
  dialogModel,
  layoutModel,
  layoutProperty,
  type ObjectModel,
  pageModel,
} from "./objects.ts";
import type { Dialog, Layout, Page, Spec } from "./spec.ts";

// The spec as plain Playwright: a class per page (pages/), a component object
// per layout and dialog, a test per journey (tests/, as the spec's folders
// are), each step a `test.step` and each line one of its own, so a failure
// names the line of the spec that failed. Nothing here needs pomspec to run.
//
// With POM_SHOTS (`pom shots`), a test also pictures its journey's moments: its
// start, then the screen after each acting line, once the lines after it have
// seen it settle (moments.ts). Each picture goes to `.pom/run/` through
// `toHaveScreenshot` (it waits for two still frames and hides the video's
// captions); `pom shots` keeps the journey only when every width passed. A
// `video-<width>` project plays the journey again, recorded, at a person's pace; with
// POM_VIDEOS too (`pom videos`), as a video for pomspec, by pom's own reel (reel.ts),
// the one thing a test loads of pom's, and only then.

const HEADER = "// Generated by pom from the spec. Edit the spec, not this file.\n";

/** What `generate` writes, and so all it ever removes: the run, the cache and the videos stay. */
const OWN = ["pages", "tests", "journeys", "pom.ts", "playwright.config.ts", ".gitignore"];

const fields = (model: ObjectModel) =>
  model.controls.map((c) => `  readonly ${c.property}: Locator;`);
const assigns = (model: ObjectModel) =>
  model.controls.map((c) => `    this.${c.property} = ${c.locator};`);

function pathPattern(page: Page): string {
  const body = page.segments
    .map((segment) =>
      segment.startsWith("[") ? "[^/?#]+" : segment.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&"),
    )
    .join("\\/");
  return `/^https?:\\/\\/[^/]+\\/${body}${body ? "\\/?" : ""}(?:[?#].*)?$/`;
}

function pageFile(page: Page): string {
  const model = pageModel(page);
  const params = page.segments.filter((s) => s.startsWith("[")).map((s) => s.slice(1, -1));
  // A segment's name is a key, quoted: `[project-id]` is `params["project-id"]`.
  const url = `/${page.segments.map((s) => (s.startsWith("[") ? `\${params[${JSON.stringify(s.slice(1, -1))}]}` : s)).join("/")}`;
  const imports = [
    ...page.layouts.map((l) => `import { ${l.className} } from "./${l.className}.ts";`),
    ...page.dialogs.map((d) => `import { ${d.className} } from "./${d.className}.ts";`),
  ];
  return `${HEADER}import { expect, type Locator, type Page } from "@playwright/test";
${imports.join("\n")}${imports.length ? "\n" : ""}
/** ${page.route} */
export class ${page.className} {
  readonly page: Page;
${[
  ...page.layouts.map((l) => `  readonly ${layoutProperty(l)}: ${l.className};`),
  ...page.dialogs.map((d) => `  readonly ${d.property}: ${d.className};`),
  ...fields(model),
].join("\n")}

  constructor(page: Page) {
    this.page = page;
${[
  ...page.layouts.map((l) => `    this.${layoutProperty(l)} = new ${l.className}(page);`),
  ...page.dialogs.map((d) => `    this.${d.property} = new ${d.className}(page);`),
  ...assigns(model),
].join("\n")}
  }

  async goto(${params.length ? `params: { ${params.map((p) => `${JSON.stringify(p)}: string`).join("; ")} }` : ""}) {
    await this.page.goto(${params.length ? `\`${url}\`` : JSON.stringify(url)});
    await this.expectLoaded();
  }

  /** At this page. What is on it, each control's own step finds. */
  async expectLoaded() {
    await expect(this.page).toHaveURL(${pathPattern(page)});
  }
}
`;
}

function layoutFile(layout: Layout): string {
  const model = layoutModel(layout);
  return `${HEADER}import type { Locator, Page } from "@playwright/test";

/** What every page under ${path.basename(layout.dir)}/ shares. */
export class ${layout.className} {
  readonly page: Page;
${fields(model).join("\n")}

  constructor(page: Page) {
    this.page = page;
${assigns(model).join("\n")}
  }
}
`;
}

function dialogFile(dialog: Dialog): string {
  const model = dialogModel(dialog);
  return `${HEADER}import { expect, type Locator, type Page } from "@playwright/test";

/** The "${dialog.name}" ${dialog.kind}. */
export class ${dialog.className} {
  readonly page: Page;
  readonly root: Locator;
${fields(model).join("\n")}

  constructor(page: Page) {
    this.page = page;
    this.root = page.getByRole(${JSON.stringify(dialog.kind)}, { name: ${JSON.stringify(dialog.name)}, exact: true });
${assigns(model).join("\n")}
  }

  async expectOpen() {
    await expect(this.root).toBeVisible();
  }
}
`;
}

/** A string as the test writes it: single quotes when that spares escaping a Gherkin line's own. */
const quote = (text: string) =>
  text.includes('"') && !/['\\]/.test(text) ? `'${text}'` : JSON.stringify(text);

const lineStep = ({ code, line }: Call, indent: string) =>
  `${indent}await test.step(${quote(line.source)}, async () => {\n${indent}  ${code};\n${indent}});`;

/**
 * A line as the generated test tells `say()` of it, for `pom videos`' reel: its line in
 * the .feature, its verb, and what it acts on, or what a `Then` proves is on the
 * screen (from its assertion).
 */
function atOf(call: Call): string {
  const shown =
    call.target ??
    /^await expect\((.+?)\)\.(?:toBeVisible|toContainText)\(/.exec(call.code)?.[1] ??
    /^await (.+)\.expectOpen\(\)$/.exec(call.code)?.[1]?.concat(".root") ??
    null;
  return `{ line: ${call.line.line}, target: ${shown ? `() => ${shown}` : "null"}, verb: ${JSON.stringify(call.line.action.verb)} }`;
}

/** A moment as the generated test passes it to `moment()`: its static part. */
function momentCall(planned: Planned, indent: string): string {
  const { target, ...seen } = planned;
  const at = JSON.stringify({
    after: seen.after,
    id: seen.id,
    index: seen.index,
    journey: seen.journey,
    next: seen.next,
    page: seen.page,
    role: seen.role,
    state: seen.state,
    step: seen.step,
  });
  return `${indent}await moment(page, ${at}, ${target ? `() => ${target}` : "null"});`;
}

/**
 * A journey's lines as test steps; with its moments (a journey's own test), each
 * taken before the acting line it precedes, the last at the end, and the video's
 * captions and lines between them. An entry journey (a sign-in) has none.
 */
function body(
  compiled: Compiled,
  moments: ReadonlyArray<Planned & Readonly<{ before: Call | null }>> | null,
): Array<string> {
  const out: Array<string> = [];
  const before = new Map(moments?.flatMap((m) => (m.before ? [[m.before, m]] : [])) ?? []);
  const lines = (calls: ReadonlyArray<Call>, indent: string) => {
    for (const call of calls) {
      const planned = before.get(call);
      if (planned) out.push(momentCall(planned, indent));
      if (moments) out.push(`${indent}await say(page, ${quote(call.line.source)}, ${atOf(call)});`);
      out.push(lineStep(call, indent));
    }
  };
  for (const page of compiled.pages)
    out.push(`  const ${pageVariable(page)} = new ${page.className}(page);`);
  if (compiled.background.length) {
    out.push(`  await test.step("Background", async () => {`);
    lines(compiled.background, "    ");
    out.push(`  });`);
  }
  // The video starts once the journey's own steps do: a sign-in played first is not its story.
  if (moments) out.push(`  await begin(page, ${JSON.stringify(moments[0]!.journey)});`);
  for (const step of compiled.steps) {
    out.push(`  await test.step(${JSON.stringify(step.caption)}, async () => {`);
    if (moments) out.push(`    await caption(page, ${JSON.stringify(step.caption)});`);
    lines(step.calls, "    ");
    out.push(`  });`);
  }
  const last = moments?.at(-1);
  if (last) {
    out.push(momentCall(last, "  "));
    out.push(`  await end(page);`);
  }
  return out;
}

const uses = (compiled: Compiled, call: string) =>
  [...compiled.background, ...compiled.steps.flatMap((s) => s.calls)].some((c) =>
    c.code.includes(`${call}(`),
  );

function imports(compiled: Compiled, up: string, extra: ReadonlyArray<string>): Array<string> {
  const helpers = [
    ...(uses(compiled, "unique") ? ["unique"] : []),
    ...(uses(compiled, "signIn") ? ["signIn"] : []),
    ...extra,
  ];
  return [
    ...compiled.pages.map((p) => `import { ${p.className} } from "${up}/pages/${p.className}.ts";`),
    ...compiled.entries.map(
      (j) => `import { ${journeyFunction(j)} } from "${up}/journeys/${journeyFunction(j)}.ts";`,
    ),
    ...(helpers.length ? [`import { ${helpers.sort().join(", ")} } from "${up}/pom.ts";`] : []),
  ];
}

/** A journey's id: its file, relative to the spec, without `.feature`. */
export const journeyId = (spec: Spec, journey: Journey) =>
  path
    .relative(spec.root, journey.file)
    .replace(/\.feature$/, "")
    .split(path.sep)
    .join("/");

function testFile(
  compiled: Compiled,
  spec: Spec,
  out: string,
  file: string,
  reset: boolean,
): string {
  const up = path.relative(path.dirname(file), out) || ".";
  const id = journeyId(spec, compiled.journey);
  const moments = plan(compiled, id);
  return `${HEADER}// ${path.relative(spec.root, compiled.journey.file)}
import { expect, test } from "@playwright/test";
${imports(compiled, up, ["begin", "caption", "end", "finish", "moment", ...(reset ? ["reset"] : []), "say"]).join("\n")}
${reset ? "\ntest.beforeEach(reset);\n" : ""}
test.afterEach(finish);

test(${JSON.stringify(compiled.journey.title)}, async ({ page }) => {
${body(compiled, moments).join("\n")}
});
`;
}

/** A journey another plays first, to sign in: the same steps, as a function. */
function journeyFile(compiled: Compiled, spec: Spec): string {
  return `${HEADER}// ${path.relative(spec.root, compiled.journey.file)}
import { expect, type Page, test } from "@playwright/test";
${imports(compiled, "..", []).join("\n")}

/** ${compiled.journey.title}: who it ends as is who it signs in. */
export async function ${journeyFunction(compiled.journey)}(page: Page) {
${body(compiled, null).join("\n")}
}
`;
}

/** How the video paces a journey, after the kit's player (`TEMPO`, packages/kit/src/player/stage.ts). */
const PACE = { hold: 700, lead: 900, settle: 1200 };

function helpers(config: Config): string {
  const settings = {
    clock: config.clock,
    dir: config.dir,
    mask: config.mask,
    pace: PACE,
    reel: REEL,
    reset: config.reset,
    roles: Object.fromEntries(
      Object.entries(config.roles).map(([role, { signIn }]) => [
        role,
        path.resolve(config.dir, signIn),
      ]),
    ),
    stylePath: config.stylePath,
  };
  return `${HEADER}import { execSync } from "node:child_process";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { expect, type Locator, type Page, test, type TestInfo } from "@playwright/test";

const SETTINGS: {
  clock: string | null;
  dir: string;
  mask: Array<string>;
  pace: { hold: number; lead: number; settle: number };
  reel: string;
  reset: string | null;
  roles: Record<string, string>;
  stylePath: string | null;
} = ${JSON.stringify(settings, null, 2)};

const marks = new Map<string, string>();

/**
 * This test's own mark, in every value it makes unique: one per test, so two
 * journeys a worker plays one after another never meet each other's account.
 */
export function mark(): string {
  const id = test.info().testId;
  let made = marks.get(id);
  if (!made) {
    made = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
    marks.set(id, made);
  }
  return made;
}

/** An email made this test's own (ana@example.com → ana+<mark>@example.com). */
export function unique(text: string): string {
  return text.replace(/([A-Za-z0-9._%-]+)@([A-Za-z0-9.-]+\\.[A-Za-z]+)/g, \`$1+\${mark()}@$2\`);
}

/** The width this test runs at: its project's name, the video's included. */
export const width = () => test.info().project.name.replace(/^video-/, "");

const shooting = () => !!process.env.POM_SHOTS;
const recording = () => shooting() && test.info().project.name.startsWith("video-");

/** What a line is, for \`pom videos\`' reel: its line in the .feature, its verb, what it is about. */
type At = { line: number; target: (() => Locator) | null; verb: string };
type Reel = {
  begin(page: Page, info: TestInfo, journey: string, mark: () => string | null): Promise<void>;
  chapter(page: Page, info: TestInfo, title: string): Promise<void>;
  finish(page: Page, info: TestInfo): Promise<void>;
  hold(page: Page, info: TestInfo): Promise<void>;
  say(page: Page, info: TestInfo, line: string, at?: At): Promise<void>;
};
let reeled: Promise<Reel> | null = null;
/**
 * With POM_VIDEOS (\`pom videos\`), the recorded run is a video for pomspec: no captions
 * or pointer drawn into it (pomspec's player draws them), and what happened when kept
 * beside it by pom's reel.
 */
const reeling = () => recording() && !!process.env.POM_VIDEOS;
const reel = () => (reeled ??= import(pathToFileURL(SETTINGS.reel).href) as Promise<Reel>);

/** The config's reset, before each journey. */
export async function reset() {
  if (SETTINGS.reset) execSync(SETTINGS.reset, { cwd: SETTINGS.dir, stdio: "inherit" });
}

/** Signs in as a role the config signs in itself: its module's default export. */
export async function signIn(page: Page, role: string) {
  const file = SETTINGS.roles[role];
  if (!file) throw new Error(\`pom.config.ts signs in no "\${role}"\`);
  const module = (await import(pathToFileURL(file).href)) as { default: (page: Page) => Promise<void> };
  await module.default(page);
}

/** This test's mark taken out of the screen (inputs and text), and how to put it back. */
async function unmark(page: Page): Promise<() => Promise<void>> {
  const id = test.info().testId;
  if (!marks.has(id)) return async () => {};
  await page.evaluate((mark) => {
    const undo: Array<() => void> = [];
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    for (let node = walker.nextNode(); node; node = walker.nextNode()) {
      const text = node;
      const was = text.nodeValue ?? "";
      if (!was.includes(mark)) continue;
      text.nodeValue = was.replaceAll(mark, "");
      undo.push(() => (text.nodeValue = was));
    }
    for (const field of document.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>("input, textarea")) {
      const was = field.value;
      if (!was.includes(mark)) continue;
      field.value = was.replaceAll(mark, "");
      undo.push(() => (field.value = was));
    }
    (window as unknown as { pomUndo: Array<() => void> }).pomUndo = undo;
  }, \`+\${marks.get(id)}\`);
  return async () => {
    await page.evaluate(() => {
      for (const undo of (window as unknown as { pomUndo?: Array<() => void> }).pomUndo ?? []) undo();
    });
  };
}

/**
 * The page's outline, what is masked left out: a covered region never makes a
 * checkpoint. With \`boxes\`, each node says where it is on the screen.
 */
export async function outline(page: Page, boxes = false): Promise<string> {
  const hidden = ["iframe", ...SETTINGS.mask];
  await page.evaluate((selectors) => {
    for (const selector of selectors) {
      for (const element of document.querySelectorAll(selector)) {
        if (element.hasAttribute("data-pom-hidden")) continue;
        element.setAttribute("data-pom-hidden", element.getAttribute("aria-hidden") ?? "");
        element.setAttribute("aria-hidden", "true");
      }
    }
  }, hidden);
  try {
    return await page.locator("body").ariaSnapshot({ boxes });
  } finally {
    await page.evaluate(() => {
      for (const element of document.querySelectorAll("[data-pom-hidden]")) {
        const was = element.getAttribute("data-pom-hidden");
        if (was) element.setAttribute("aria-hidden", was);
        else element.removeAttribute("aria-hidden");
        element.removeAttribute("data-pom-hidden");
      }
    });
  }
}

/** Where a control is, rounded; none when it is not on the screen yet. */
async function boxOf(locator: Locator): Promise<[number, number, number, number] | null> {
  if ((await locator.count()) === 0) return null;
  const box = await locator.first().boundingBox({ timeout: 1000 }).catch(() => null);
  return box ? [Math.round(box.x), Math.round(box.y), Math.round(box.width), Math.round(box.height)] : null;
}

type Planned = {
  after: { line: number; source: string } | null;
  id: string;
  index: number;
  journey: string;
  next: { line: number; name: string | null; role: string | null; verb: string } | null;
  page: string | null;
  role: string;
  state: string | null;
  step: number;
};

type Video = {
  caption: string;
  chapters: Array<{ caption: string; ms: number }>;
  file: string;
  moments: Array<{ id: string; ms: number }>;
  overlay: { dispose(): Promise<void> } | null;
  t0: number;
};

const videos = new Map<string, Video>();

/**
 * With POM_SHOTS, the screen as it is now: a picture into \`.pom/run/\`, still (no
 * animations, no caret, embedded frames and the config's masks covered) and with
 * this test's mark taken out of it (ana+<mark>@example.com reads ana@example.com,
 * as the spec says), then put back; with its outline and where the next control is.
 * Recorded, it holds the screen a moment instead, and notes when.
 */
/**
 * The screen ready for what comes next: the network quiet and the next line's control
 * drawn, each for at most 5 s. Two still frames alone pass a page still loading.
 */
async function settled(page: Page, next: (() => Locator) | null) {
  await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => {});
  if (next) await next().first().waitFor({ state: "visible", timeout: 5000 }).catch(() => {});
}

export async function moment(page: Page, planned: Planned, next: (() => Locator) | null) {
  if (!shooting()) return;
  const info = test.info();
  if (reeling()) return (await reel()).hold(page, info);
  if (recording()) {
    const video = videos.get(info.testId);
    if (!video) return;
    video.moments.push({ id: planned.id, ms: Date.now() - video.t0 });
    await page.waitForTimeout(SETTINGS.pace.hold);
    return;
  }
  if (SETTINGS.clock && !(info as unknown as { pomClock?: boolean }).pomClock) {
    (info as unknown as { pomClock?: boolean }).pomClock = true;
    await page.clock.setFixedTime(new Date(SETTINGS.clock));
  }
  await settled(page, next);
  const box = next ? await boxOf(next()) : null;
  const undo = await unmark(page);
  try {
    await expect(page).toHaveScreenshot([...planned.journey.split("/"), width(), \`\${planned.id}.png\`], {
      animations: "disabled",
      caret: "hide",
      mask: [page.locator("iframe"), ...SETTINGS.mask.map((selector) => page.locator(selector))],
      maskColor: "#d4d4d8",
      ...(SETTINGS.stylePath ? { stylePath: SETTINGS.stylePath } : {}),
    });
  } finally {
    await undo();
  }
  const structure = await outline(page);
  await info.attach("pom:moment", {
    body: JSON.stringify({ ...planned, box, structure, width: width() }),
    contentType: "application/json",
  });
}

const escape = (text: string) =>
  text.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

/** The video's subtitles, as a video player draws them: the step above, the line below. */
async function subtitle(page: Page, video: Video, line: string | null) {
  await video.overlay?.dispose();
  video.overlay = await page.screencast.showOverlay(
    \`<div style="position:fixed;left:0;right:0;bottom:28px;display:flex;flex-direction:column;align-items:center;gap:6px;pointer-events:none;font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif">\` +
      \`<div style="background:rgba(8,8,8,.75);color:#fff;font-size:15px;padding:3px 10px;border-radius:3px;opacity:.85">\${escape(video.caption)}</div>\` +
      (line ? \`<div style="background:rgba(8,8,8,.75);color:#fff;font-size:22px;line-height:1.3;padding:4px 12px;border-radius:3px;max-width:80%;text-align:center">\${escape(line)}</div>\` : "") +
      \`</div>\`,
  );
}

/** Recorded: the video starts, the pointer shows each action. */
export async function begin(page: Page, journey: string) {
  if (!recording()) return;
  const info = test.info();
  if (reeling()) return (await reel()).begin(page, info, journey, () => marks.get(info.testId) ?? null);
  const file = path.join(process.env.POM_RUN!, "videos", \`\${journey}.\${width()}.webm\`);
  mkdirSync(path.dirname(file), { recursive: true });
  const size = page.viewportSize();
  await page.screencast.start({ path: file, ...(size ? { size } : {}) });
  await page.screencast.showActions({ cursor: "pointer", duration: 400 });
  videos.set(info.testId, { caption: "", chapters: [], file, moments: [], overlay: null, t0: Date.now() });
}

/** Recorded: a step begins, its caption shown a beat before anything happens. */
export async function caption(page: Page, text: string) {
  if (!recording()) return;
  if (reeling()) return (await reel()).chapter(page, test.info(), text);
  const video = videos.get(test.info().testId);
  if (!video) return;
  video.caption = text;
  video.chapters.push({ caption: text, ms: Date.now() - video.t0 });
  await subtitle(page, video, null);
  await page.waitForTimeout(SETTINGS.pace.lead);
}

/** Recorded: the line about to happen, as its subtitle. */
export async function say(page: Page, line: string, at?: At) {
  if (!recording()) return;
  if (reeling()) return (await reel()).say(page, test.info(), line, at);
  const video = videos.get(test.info().testId);
  if (video) await subtitle(page, video, line);
}

/** Recorded: the end held a beat, the video saved, and what happened when noted beside it. */
export async function end(page: Page) {
  if (!recording() || reeling()) return;
  const info = test.info();
  const video = videos.get(info.testId);
  if (!video) return;
  await page.waitForTimeout(SETTINGS.pace.settle);
  await video.overlay?.dispose();
  await page.screencast.stop();
  await info.attach("pom:video", {
    body: JSON.stringify({ chapters: video.chapters, file: video.file, moments: video.moments, ms: Date.now() - video.t0 }),
    contentType: "application/json",
  });
}

/** After each journey, passed or not: \`pom videos\`' video ends where the journey did. */
export async function finish({ page }: { page: Page }) {
  if (reeling()) await (await reel()).finish(page, test.info());
}
`;
}

/** A width's Playwright options, from a device or a desktop's. */
function widthUse(config: Config, name: string): string {
  const width = config.widths[name]!;
  const base = width.device
    ? `devices[${JSON.stringify(width.device)}]`
    : `devices["Desktop Chrome"]`;
  const own = {
    ...(width.viewport ? { viewport: width.viewport } : {}),
    ...(width.deviceScaleFactor !== undefined
      ? { deviceScaleFactor: width.deviceScaleFactor }
      : {}),
    ...(width.isMobile !== undefined ? { isMobile: width.isMobile } : {}),
    ...(width.hasTouch !== undefined ? { hasTouch: width.hasTouch } : {}),
  };
  return `{ ...${base}, ...${JSON.stringify(own)} }`;
}

function playwrightConfig(config: Config, reporter: string): string {
  const widths = Object.keys(config.widths);
  const projects = [
    ...widths.map(
      (name) => `    { name: ${JSON.stringify(name)}, use: ${widthUse(config, name)} },`,
    ),
    // Recorded without a trace: tracing's screenshots would start the page's capture first, at 800px.
    ...(config.video?.widths ?? []).map(
      (name) =>
        `    { name: ${JSON.stringify(`video-${name}`)}, use: { ...${widthUse(config, name)}, trace: "off" } },`,
    ),
  ];
  // The app's own server; a base run starts the base's on a port of its own ($PORT).
  const web = config.webServer;
  const server = web
    ? `
  webServer: {
    command: ${JSON.stringify(web.command)},
    cwd: ${JSON.stringify(path.resolve(config.dir, web.cwd ?? "."))},
    env: { ...${JSON.stringify(web.env ?? {})}, ...(process.env.PORT ? { PORT: process.env.PORT } : {}) },
    reuseExistingServer: ${web.reuseExistingServer ?? true},
    timeout: ${web.timeout ?? 60_000},
    ${web.url || !web.port ? `url: process.env.PORT ? ${JSON.stringify(`http://localhost:`)} + process.env.PORT : ${JSON.stringify(web.url ?? config.baseURL ?? "")},` : `port: process.env.PORT ? Number(process.env.PORT) : ${web.port},`}
  },`
    : "";
  return `${HEADER}import { defineConfig, devices } from "@playwright/test";

// \`pom shots\` reports through pom's own reporter (one line a journey and width),
// which also keeps \`toHaveScreenshot\`'s "writing actual" notes out of the output.
const shots = !!process.env.POM_SHOTS;
const ws = process.env.POM_WS;

export default defineConfig({
  expect: {
    toHaveScreenshot: {
      maxDiffPixelRatio: ${config.threshold.ratio},
      pathTemplate: "run/{arg}{ext}",
      threshold: ${config.threshold.pixel},
      timeout: 15_000,
    },
  },
  fullyParallel: false,
  outputDir: "./results",
  projects: [
${projects.join("\n")}
  ],
  reporter: shots ? [[${JSON.stringify(reporter)}]] : [["list"]],
  retries: 0,
  // \`pom map\` crawls with a test of its own, beside the journeys'.
  testDir: process.env.POM_TESTS ?? "./tests",
  timeout: 120_000,
  updateSnapshots: "changed",
  use: {
    baseURL: process.env.POM_BASE_URL,
    colorScheme: ${JSON.stringify(config.colorScheme)},
    locale: ${JSON.stringify(config.locale)},
    reducedMotion: "reduce",
    timezoneId: ${JSON.stringify(config.timezoneId)},
    trace: "retain-on-failure",
    ...(ws ? { connectOptions: { exposeNetwork: "<loopback>", wsEndpoint: ws } } : {}),
  },${server}
  // Journeys share one app: one at a time, so a reset or a list never sees another's.
  workers: 1,
});
`;
}

/** Pom's reporter, beside this file: \`.ts\` from the source, \`.js\` once built. */
export const REPORTER = fileURLToPath(
  new URL(`./reporter${path.extname(fileURLToPath(import.meta.url))}`, import.meta.url),
);

/** `pom videos`' reel (reel.ts), beside this file, which a recorded test loads only for it. */
const REEL = fileURLToPath(
  new URL(`./reel${path.extname(fileURLToPath(import.meta.url))}`, import.meta.url),
);

export type GenerateOptions = Readonly<{
  check?: CheckOptions;
  config?: Config;
  /** Write what checks (every page, the journeys that pass) even when some do not. */
  partial?: boolean;
}>;

export function generate(
  spec: Spec,
  out: string,
  options: GenerateOptions = {},
): { problems: Array<Problem>; written: Array<string> } {
  const config = options.config ?? resolveConfig({}, path.dirname(spec.root), null);
  const check: CheckOptions = options.check ?? {
    signIns: new Set(Object.keys(config.roles)),
  };
  const { compiled, problems } = checkSpec(spec, check);
  if (problems.length && !options.partial) return { problems, written: [] };
  for (const own of OWN) rmSync(path.join(out, own), { force: true, recursive: true });
  const written: Array<string> = [];
  const write = (file: string, text: string) => {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, text);
    written.push(file);
  };
  const layouts = new Map(spec.pages.flatMap((p) => p.layouts).map((l) => [l.className, l]));
  for (const layout of layouts.values())
    write(path.join(out, "pages", `${layout.className}.ts`), layoutFile(layout));
  for (const page of spec.pages) {
    write(path.join(out, "pages", `${page.className}.ts`), pageFile(page));
    for (const dialog of page.dialogs)
      write(path.join(out, "pages", `${dialog.className}.ts`), dialogFile(dialog));
  }
  for (const c of compiled) {
    const relative = path.relative(spec.root, c.journey.file).replace(/\.feature$/, ".spec.ts");
    const file = path.join(out, "tests", relative);
    write(file, testFile(c, spec, out, file, config.reset !== null));
  }
  // Every role's way in, used by a journey or not: \`pom map\` signs in with them too.
  const entries = new Set<Journey>([
    ...compiled.flatMap((c) => c.entries),
    ...[...spec.roles].flatMap((role) => {
      if (role === "visitor" || config.roles[role]) return [];
      const entry = entryFor(spec, role);
      return entry && compiled.some((c) => c.journey === entry) ? [entry] : [];
    }),
  ]);
  for (const entry of entries) {
    const played = compile(spec, entry, check).compiled!;
    write(path.join(out, "journeys", `${journeyFunction(entry)}.ts`), journeyFile(played, spec));
  }
  write(path.join(out, "pom.ts"), helpers(config));
  write(path.join(out, "playwright.config.ts"), playwrightConfig(config, REPORTER));
  // Nothing pom writes here is the repository's: the run, the pictures, the videos.
  write(path.join(out, ".gitignore"), "*\n");
  return { problems, written };
}
