import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { entryFor, journeyFunction } from "./check.ts";
import { type Config, findConfig } from "./config.ts";
import { VISITOR } from "./feature.ts";
import { inventory, play, routeOf } from "./map.ts";
import { readOutline } from "./outline.ts";
import { pageAt, type Spec } from "./spec.ts";
import { type Combo, type Written, writePage } from "./trees.ts";

// `pom snapshot <path>…`: pages as the app shows them now, as each role asked for, at
// every width. Each is pictured, its outline kept with where each node is on the
// screen (`[box=x,y,width,height]`: a picture's element found in its tree), and its
// tree written from them: its landmarks, headings, controls and links. A role signs
// in as journeys do, through its config or the journey that makes it.

export type Snapped = Readonly<{
  /** Where the page landed (a redirect goes elsewhere). */
  at: string;
  /** `.pom/snapshot/<route>/<role>.<width>.png` and `.aria.yml`, by width. */
  files: Readonly<Record<string, { outline: string; picture: string }>>;
  path: string;
  role: string;
}>;

const slug = (at: string) => at.replace(/^\/|\/$/g, "").replace(/[^a-zA-Z0-9]+/g, "-") || "home";

type Way = Readonly<{ entry: string | null; role: string; viaConfig: boolean }>;

/** A folder on disk that holds a spec: a pom.config beside or in it, or journeys and trees. */
function holdsSpec(dir: string): boolean {
  if (findConfig(dir) !== null) return true;
  try {
    return readdirSync(dir).some(
      (entry) => entry.endsWith(".feature") || entry.endsWith(".tree.yml"),
    );
  } catch {
    return false;
  }
}

/** Whether `at` is `dir` or inside it. */
const inside = (dir: string, at: string) => {
  const relative = path.relative(dir, at);
  return relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
};

/**
 * `pom snapshot`'s arguments: the spec, a folder on disk, and the pages, each an address
 * from a slash. An argument from a slash that is also on disk is the spec when the folder
 * holds one, said in `notes`; else a page, said only when the folder or file could have
 * been meant, inside one of `near` (the folder pom runs in, its repository): `/` and
 * `/home` are on every disk, and as plainly pages.
 */
export function snapshotArgs(
  args: ReadonlyArray<string>,
  near: ReadonlyArray<string> = [process.cwd()],
): { notes: Array<string>; paths: Array<string>; specs: Array<string> } {
  const notes: Array<string> = [];
  const paths: Array<string> = [];
  const specs: Array<string> = [];
  for (const arg of args) {
    if (!arg.startsWith("/")) {
      specs.push(arg);
      continue;
    }
    const onDisk = statSync(arg, { throwIfNoEntry: false });
    if (onDisk?.isDirectory() && holdsSpec(arg)) {
      notes.push(`${arg}: read as the spec, the folder on disk, not a page's address`);
      specs.push(arg);
      continue;
    }
    if (onDisk && near.some((dir) => inside(dir, arg))) {
      notes.push(
        `${arg}: read as a page's address: the ${onDisk.isDirectory() ? "folder" : "file"} on disk there holds no spec`,
      );
    }
    paths.push(arg);
  }
  return { notes, paths, specs };
}

/** How the snapshot becomes each role, or why it cannot. */
export function waysIn(
  spec: Spec,
  config: Config,
  roles: ReadonlyArray<string>,
  checked: ReadonlySet<string>,
): Array<Way> | string {
  const ways: Array<Way> = [];
  for (const role of roles) {
    if (role === VISITOR) ways.push({ entry: null, role, viaConfig: false });
    else if (config.roles[role]) ways.push({ entry: null, role, viaConfig: true });
    else {
      const entry = entryFor(spec, role);
      if (!entry)
        return `nothing signs in as the "${role}": no journey ends as them, and pom.config.ts has no roles.${role}.signIn`;
      if (!checked.has(entry.file))
        return `to sign in as the "${role}", ${path.relative(process.cwd(), entry.file)} must check first: snapshot its pages as the visitor`;
      ways.push({ entry: journeyFunction(entry), role, viaConfig: false });
    }
  }
  return ways;
}

function snapshotTest(input: {
  mask: ReadonlyArray<string>;
  paths: ReadonlyArray<string>;
  ways: ReadonlyArray<Way>;
}): string {
  const entries = [...new Set(input.ways.flatMap((w) => (w.entry ? [w.entry] : [])))];
  return `// Generated by pom snapshot. Edit the spec, not this file.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { test } from "@playwright/test";
import { outline, signIn } from "../pom.ts";
${entries.map((name) => `import { ${name} } from "../journeys/${name}.ts";`).join("\n")}

const PATHS = ${JSON.stringify(input.paths)};
const MASK = ${JSON.stringify(input.mask)};

${input.ways
  .map(
    (w) => `test(${JSON.stringify(`snapshot as ${w.role}`)}, async ({ page }, info) => {
  ${w.viaConfig ? `await signIn(page, ${JSON.stringify(w.role)});` : w.entry ? `await ${w.entry}(page);` : ""}
  const dir = path.join(process.env.POM_RUN!, "snapshot", ${JSON.stringify(w.role)}, info.project.name);
  mkdirSync(dir, { recursive: true });
  const pages: Array<unknown> = [];
  for (const [index, at] of PATHS.entries()) {
    await page.goto(at);
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => {});
    const picture = path.join(dir, index + ".png");
    await page.screenshot({ animations: "disabled", caret: "hide", fullPage: true, mask: [page.locator("iframe"), ...MASK.map((s) => page.locator(s))], maskColor: "#d4d4d8", path: picture });
    const aria = path.join(dir, index + ".aria.yml");
    writeFileSync(aria, await outline(page, true));
    pages.push({ aria, at: new URL(page.url()).pathname, path: at, picture });
  }
  writeFileSync(path.join(dir, "pages.json"), JSON.stringify(pages));
});`,
  )
  .join("\n\n")}
`;
}

/** Snapshots `paths` as each of `ways`' roles at every width; writes their trees. */
export function snapshot(input: {
  base: string;
  config: Config;
  out: string;
  paths: ReadonlyArray<string>;
  spec: Spec;
  ways: ReadonlyArray<Way>;
}): { snapped: Array<Snapped>; status: number; trees: Array<Written> } {
  const { config, out, spec } = input;
  const widths = Object.keys(config.widths);
  const tests = path.join(out, "snapshot");
  mkdirSync(tests, { recursive: true });
  writeFileSync(
    path.join(tests, "snapshot.spec.ts"),
    snapshotTest({ mask: config.mask, paths: input.paths, ways: input.ways }),
  );
  const run = path.join(out, "run");
  rmSync(path.join(run, "snapshot"), { force: true, recursive: true });
  const played = play({ base: input.base, out, run, tests: "./snapshot", widths });

  // What each path showed, kept by its route, role and width; then each route's trees.
  const snapped: Array<Snapped> = [];
  const byRoute = new Map<
    string,
    { at: string; role: string; seen: Array<{ combo: Combo; tree: ReturnType<typeof inventory> }> }
  >();
  for (const { role } of input.ways) {
    for (const width of widths) {
      const file = path.join(run, "snapshot", role, width, "pages.json");
      if (!existsSync(file)) continue;
      const pages = JSON.parse(readFileSync(file, "utf8")) as Array<{
        aria: string;
        at: string;
        path: string;
        picture: string;
      }>;
      for (const page of pages) {
        const route = routeOf(page.at);
        const keep = path.join(out, "snapshot", slug(route));
        mkdirSync(keep, { recursive: true });
        const files = {
          outline: path.join(keep, `${role}.${width}.aria.yml`),
          picture: path.join(keep, `${role}.${width}.png`),
        };
        copyFileSync(page.aria, files.outline);
        copyFileSync(page.picture, files.picture);
        const done = snapped.find((s) => s.path === page.path && s.role === role);
        if (done) (done.files as Record<string, typeof files>)[width] = files;
        else snapped.push({ at: page.at, files: { [width]: files }, path: page.path, role });
        const key = `${route}\u0000${role}`;
        const at = byRoute.get(key) ?? { at: page.at, role, seen: [] };
        at.seen.push({
          combo: { role, state: null, width },
          tree: inventory(readOutline(readFileSync(page.aria, "utf8")), true),
        });
        byRoute.set(key, at);
      }
    }
  }
  const routes = new Map<
    string,
    { at: string; role: string; seen: Array<{ combo: Combo; tree: ReturnType<typeof inventory> }> }
  >();
  for (const [key, at] of byRoute) {
    const route = key.split("\u0000")[0]!;
    const had = routes.get(route);
    if (had) had.seen.push(...at.seen);
    else routes.set(route, { ...at, seen: [...at.seen] });
  }
  const trees: Array<Written> = [];
  for (const [route, { at, role, seen }] of routes) {
    // A page the spec has goes where it is (its group); a new one under its route.
    const dir =
      pageAt(spec, at, role)?.page.dir ?? path.join(spec.root, ...route.split("/").filter(Boolean));
    trees.push(...writePage(dir, seen));
  }
  return { snapped, status: played.status ?? 1, trees };
}
