import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { type Journey, readFeature, SpecError, VISITOR } from "./feature.ts";
import { type Node, readTree, walk } from "./tree.ts";
import type { Width } from "./types.ts";

export type { Width };

// A spec folder is routed the way Next.js routes `app/`: a folder is a path
// segment, `[slug]` a dynamic one, `(group)` none at all. In a folder,
// `page.tree.yml` is the page at that path, `layout.tree.yml` what every page
// at or below it shares, `<name>.dialog.tree.yml` a dialog its page opens (and
// `<name>.menu.tree.yml` a menu), and
// each `<name>.feature` a journey that starts there.
//
// A page looks different by its variations: the width (the config's, desktop and
// phone by default), who acts (`# as owner`), the state the journey names (`# when
// empty`). `page.tree.yml` holds what every variation shows, `page.<variation>.tree.yml`
// what only that one does (a layout's too). A group named after a role, `(visitor)`,
// is still that role's page where two share a path; a variation says it in one page.

export const WIDTHS: ReadonlyArray<Width> = ["desktop", "phone"];

/** A tree file: `generated` when pom wrote it (its first line says so), else a person did. */
export type Plain = Readonly<{
  file: string;
  generated: boolean;
  source: string;
  tree: Array<Node>;
}>;

/** The first line of a tree pom wrote; a tree without it is a person's, and pom never rewrites it. */
export const GENERATED =
  "# generated by pom from the app (pom snapshot, pom map): delete this line to keep your edits";

/** Whether pom wrote a tree: any version of its first line. */
export const isGenerated = (source: string) => source.startsWith("# generated by pom");

/** A tree and what only some variations show: by variation (a width, a role, a state). */
export type Tree = Plain & Readonly<{ variations: Readonly<Record<string, Plain>> }>;

export type Layout = Tree & Readonly<{ className: string; dir: string }>;

/** A dialog or a menu a page opens: one node, its role the kind, its name the line's. */
export type Dialog = Tree &
  Readonly<{
    className: string;
    kind: "dialog" | "menu";
    name: string;
    property: string;
    root: Node;
  }>;

export type Page = Tree &
  Readonly<{
    className: string;
    dialogs: ReadonlyArray<Dialog>;
    dir: string;
    /** The route groups it is in, without their parentheses. */
    groups: ReadonlyArray<string>;
    /** Outermost first. */
    layouts: ReadonlyArray<Layout>;
    /** `/settings/[slug]` */
    route: string;
    segments: ReadonlyArray<string>;
  }>;

export type Spec = Readonly<{
  journeys: ReadonlyArray<Journey>;
  pages: ReadonlyArray<Page>;
  /** Every role a journey names, the visitor included. */
  roles: ReadonlySet<string>;
  root: string;
  /** The states journeys name (`# when empty`): variations, as roles and widths are. */
  states: ReadonlySet<string>;
  /** The widths the journeys are pictured at: variations too. */
  widths: ReadonlyArray<Width>;
}>;

/** Every variation a spec knows: its widths, its roles, its states. */
export const variationsOf = (spec: Spec): ReadonlySet<string> =>
  new Set([...spec.widths, ...spec.roles, ...spec.states]);

const pascal = (words: string) =>
  words
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join("");

export const camel = (words: string) => {
  const name = pascal(words);
  return name ? name[0]!.toLowerCase() + name.slice(1) : "_";
};

const isGroup = (segment: string) => /^\(.+\)$/.test(segment);

function plain(file: string): Plain {
  const source = readFileSync(file, "utf8");
  return { file, generated: isGenerated(source), source, tree: readTree(source, file) };
}

/** `<base>.tree.yml`, with what only a variation shows beside it (`<base>.<variation>.tree.yml`). */
function tree(dir: string, base: string, entries: ReadonlyArray<string>): Tree {
  const variations: Record<string, Plain> = {};
  for (const entry of entries) {
    const found = new RegExp(`^${base}\\.([a-z0-9][a-z0-9-]*)\\.tree\\.yml$`).exec(entry);
    if (found) variations[found[1]!] = plain(path.join(dir, entry));
  }
  return { ...plain(path.join(dir, `${base}.tree.yml`)), variations };
}

/** A tree and its variations' trees, as one list of nodes (only `active` ones when given). */
export const allNodes = (tree: Tree, active?: (variation: string) => boolean): Array<Node> => [
  ...tree.tree,
  ...Object.entries(tree.variations).flatMap(([name, plain]) =>
    !active || active(name) ? plain.tree : [],
  ),
];

export function readSpec(root: string, widths: ReadonlyArray<Width> = WIDTHS): Spec {
  // Said as a sentence, never as the file system's ENOENT.
  if (!statSync(root, { throwIfNoEntry: false })?.isDirectory())
    throw new SpecError(
      `No spec folder at ${path.relative(process.cwd(), root) || "."}/: run pom init to start one, or give the folder your journeys are in.`,
    );
  const pages: Array<Page> = [];
  const journeys: Array<Journey> = [];

  const visit = (dir: string, parts: Array<string>, layouts: Array<Layout>) => {
    const entries = readdirSync(dir).sort();
    const here = [...layouts];
    if (entries.includes("layout.tree.yml")) {
      const name = parts.map((part) => part.replace(/[()[\]]/g, "")).join(" ") || "root";
      here.push({
        ...tree(dir, "layout", entries),
        className: `${pascal(name)}Layout`,
        dir,
      });
    }
    const segments = parts.filter((part) => !isGroup(part));
    if (entries.includes("page.tree.yml")) {
      const named = segments.map((part) => part.replace(/[[\]]/g, "")).join(" ") || "home";
      const dialogs = entries
        .filter((entry) => /\.(dialog|menu)\.tree\.yml$/.test(entry))
        .map((entry): Dialog => {
          const kind = entry.endsWith(".menu.tree.yml") ? "menu" : "dialog";
          const read = { ...plain(path.join(dir, entry)), variations: {} };
          const root = read.tree.length === 1 ? read.tree[0] : undefined;
          if (!root || root.role !== kind || typeof root.name !== "string") {
            throw new Error(`${read.file}: a ${kind}'s tree is one node, ${kind} "Its name"`);
          }
          const base = entry.slice(0, -`.${kind}.tree.yml`.length);
          const suffix = kind === "menu" ? "Menu" : "Dialog";
          return {
            ...read,
            className: `${pascal(base)}${suffix}`,
            kind,
            name: root.name,
            property: `${camel(base)}${suffix}`,
            root,
          };
        });
      pages.push({
        ...tree(dir, "page", entries),
        className: `${pascal(named)}Page`,
        dialogs,
        dir,
        groups: parts.filter(isGroup).map((part) => part.slice(1, -1)),
        layouts: here,
        route: `/${segments.join("/")}`,
        segments,
      });
    }
    for (const entry of entries) {
      const full = path.join(dir, entry);
      if (entry.endsWith(".feature")) journeys.push(readFeature(readFileSync(full, "utf8"), full));
      // A journey's pictures (`<journey>.shots/`) are no path segment.
      else if (
        statSync(full).isDirectory() &&
        !entry.startsWith(".") &&
        !entry.endsWith(".shots")
      ) {
        visit(full, [...parts, entry], here);
      }
    }
  };

  visit(root, [], []);
  // Two pages at one path are told apart by their groups' names, in their classes too.
  const named = pages.map((page) => {
    const className = pages.some((other) => other !== page && other.route === page.route)
      ? `${pascal(page.groups.join(" "))}${page.className}`
      : page.className;
    // A dialog is its page's: two pages may each have a `delete.dialog.tree.yml`.
    const dialogs = page.dialogs.map((dialog) => ({
      ...dialog,
      className: `${className.replace(/Page$/, "")}${dialog.className}`,
    }));
    return { ...page, className, dialogs };
  });
  const roles = new Set([
    VISITOR,
    ...journeys.flatMap((journey) => [
      journey.endsAs,
      ...[...journey.background, ...journey.steps.flatMap((step) => step.lines)].map(
        (line) => line.role,
      ),
    ]),
  ]);
  const states = new Set(
    journeys.flatMap((journey) =>
      [...journey.background, ...journey.steps.flatMap((step) => step.lines)].flatMap((line) =>
        line.state ? [line.state] : [],
      ),
    ),
  );
  const spec: Spec = { journeys, pages: named, roles, root, states, widths };
  // A variation's tree names one the spec knows, or nothing would ever check it.
  const known = variationsOf(spec);
  for (const page of named) {
    for (const tree of [page, ...page.layouts]) {
      for (const [name, plain] of Object.entries(tree.variations)) {
        if (known.has(name)) continue;
        throw new Error(
          `${plain.file}: "${name}" is no width, role or state of this spec (widths: ${widths.join(", ")}; roles: ${[...roles].join(", ")}${states.size ? `; states: ${[...states].join(", ")}` : ""})`,
        );
      }
    }
  }
  return spec;
}

/** The role a page is for, when a group of its says so. */
export const roleOf = (spec: Spec, page: Page) =>
  page.groups.find((group) => spec.roles.has(group)) ?? null;

/**
 * The page a path is on, for who is acting: `/acme/main` is `/[slug]/[session]`'s,
 * with its values; `/` is the visitor's landing or a member's feed.
 */
export function pageAt(
  spec: Spec,
  at: string,
  role: string = VISITOR,
): { page: Page; params: Record<string, string> } | null {
  const wanted = at.split(/[?#]/)[0]!.split("/").filter(Boolean);
  // A static segment outranks a dynamic one, as in Next.js.
  const ranked = [...spec.pages].sort(
    (a, b) =>
      a.segments.filter((s) => s.startsWith("[")).length -
      b.segments.filter((s) => s.startsWith("[")).length,
  );
  const fitting: Array<{ page: Page; params: Record<string, string> }> = [];
  for (const page of ranked) {
    if (page.segments.length !== wanted.length) continue;
    const params: Record<string, string> = {};
    const fits = page.segments.every((segment, index) => {
      if (segment.startsWith("[")) {
        params[segment.slice(1, -1)] = wanted[index]!;
        return true;
      }
      return segment === wanted[index];
    });
    if (fits && (!fitting[0] || fitting[0].page.route === page.route)) {
      fitting.push({ page, params });
    }
  }
  if (fitting.length < 2) return fitting[0] ?? null;
  // One path, a page per role: the acting role's, else the one no role claims.
  return (
    fitting.find(({ page }) => roleOf(spec, page) === role) ??
    fitting.find(({ page }) => roleOf(spec, page) === null) ??
    null
  );
}

/** Everything a tree holds, for `I see`: names and text. */
export function words(
  trees: ReadonlyArray<Tree>,
  active?: (variation: string) => boolean,
): Array<string> {
  const out: Array<string> = [];
  for (const tree of trees) {
    for (const { node } of walk(allNodes(tree, active))) {
      if (typeof node.name === "string") out.push(node.name);
      if (node.text) out.push(node.text);
    }
  }
  return out;
}
